name: Build and test

on:
  push:
    branches:
      - "**" # This matches all branches
      - "!main" # exclude main branch

env:
  service-name: ${{ github.event.inputs.service-name }}

jobs:

  Build-Service:
    runs-on: [self-hosted, prd, vm, ubuntu-latest]
    name: Build Service
    inputs:
      java-version:
        description: "Java version"
        required: true
        default: "21"
      java-distribution:
        description: "Java distribution"
        required: false
        default: "temurin"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          overwrite-settings: false
          cache: maven

      - name: Build JAR
        run: mvn clean package

      - name: Archive JAR
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.service-name }}.jar
          path: build/libs/${{ env.service-name }}.jar
          retention-days: 5

      - name: Class Test Report
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
        if: success() || failure()
        with:
          name: Class Tests
          path: '**/build/test-results/test**/TEST-*.xml'
          reporter: java-junit